spring.application.name=Eureka-Registry
server.port=9898

#eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:9898/eureka/
