spring.application.name=apigateway
server.port=9999

eureka.client.service-url.defaultZone=http://localhost:9898/eureka

spring.cloud.gateway.server.webflux.routes[0].id=Admin-ServiceDomain
spring.cloud.gateway.server.webflux.routes[0].uri=lb://Admin-ServiceDomain
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/employee/**

spring.cloud.gateway.server.webflux.routes[1].id=Product-ServiceDomain
spring.cloud.gateway.server.webflux.routes[1].uri=lb://Product-ServiceDomain
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/product/**

spring.cloud.gateway.server.webflux.routes[2].id=User-ServiceDomain
spring.cloud.gateway.server.webflux.routes[2].uri=lb://User-ServiceDomain
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/user/**

management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=unrestricted
