spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/userdomainmodule
spring.datasource.username=root
spring.datasource.password=root

<<<<<<< HEAD
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

=======
>>>>>>> ddd55d5 (Add user docker properties)
eureka.client.service-url.defaultZone=http://host.docker.internal:9898/eureka/

logging.file.name=/app/user.log